# Generated by Django 3.1.1 on 2020-09-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='top_image',
        ),
    ]
